#+TITLE: Fenstertheater
#+SETUPFILE: https://fniessen.github.io/org-html-themes/org/theme-readtheorg.setup
#+HTML_HEAD: <script src="../spoiler.js" defer></script>
#+macro: spoiler @@html:<details><summary>$1</summary>@@
#+macro: endspoiler @@html:</details>@@
#+macro: line -----

- [[file:./index.org][Zurück]]

* Welche Eigenschaften der Menschen werden mit dieser Geschichte allgemein herausgehoben?
- Neugierde (ins Haus der anderen schauen) - Gaffen
- Wenig Privatsphäre
- Einsamkeit (die Frau hat eventuell nichts anderes, viel Zeit)
- Missverständnis (das Gefühl zu haben, es geht immer um einen selbst)

* Gibt es ein aktuelles Problem, das diese Geschichte kritisiert?
- Gaffen / Kein Schamgefühl / Voyeurismus
- Wenig Privatsphäre
    - Neugierde am Leben der anderen Menschen über ein Maß hinaus, das akzeptabel ist. Z.B.
      Bei Unfällen zuschauen und filmen
    - Aber auch: Das übermäßige Teilen des eigenen Lebens mit anderen. Z.B. TikTok, Instagram

* Welche Symbolik hat der Kontrast der Fenster. Der Mann hat ein hell erleuchtetes Fenster, die Frau ein dunkles Fenster.
- Die Frau
    + Will nicht erkannt werden
    + Die Frau ist verschlossen
    + Die Dunkelheit steht für die "schlechten" Eigenschaften der Frau: Die Neugierde, die Einsamkeit.
- Der Mann
    + Ist offener
    + Willkommen heißend
    + Lebensfroh
    + Es werden positive Eigenschaften dargestellt
Kontrast Licht und Dunkel ist häufig eine Darstellung von "gut" und "schlecht"

* Neugier bringt die Menschen weiter. Als Sucht nach neuen Skandalen ist sie aber auch eine Plage der Menschheit.
- 
